#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || { printf 'Errore: non sei in un repository git.\n'; exit 1; }
PACKAGE_JSON="$REPO_ROOT/electron/package.json"

banner "Release No Budget"

# ── Stage 1: Prerequisiti ─────────────────────────────────────────────────
stage "Prerequisiti"
say "Verifica strumenti necessari e stato del repo."

if ! command -v gh >/dev/null 2>&1; then
  warn "gh CLI non trovato."
  open_url "https://cli.github.com"
  pause "Installa gh, poi premi Enter."
fi
if ! gh auth status >/dev/null 2>&1; then
  warn "gh non autenticato. Esegui: gh auth login"
  pause "Autentica gh, poi premi Enter."
fi
if ! command -v pnpm >/dev/null 2>&1; then
  warn "pnpm non trovato. Installa con: npm install -g pnpm"
  pause "Installa pnpm, poi premi Enter."
fi

say "Remote git configurato:"
git -C "$REPO_ROOT" remote -v | head -4
printf '\n'
confirm "Il remote è corretto?" || { say "Correggi il remote e riavvia."; exit 1; }

# ── Stage 2: Nuova versione ───────────────────────────────────────────────
stage "Nuova versione"
CURRENT_VERSION=$(node -p "require('$PACKAGE_JSON').version")
say "Versione attuale: ${BOLD}${CURRENT_VERSION}${RESET}"
note "Convenzione semver: X.Y.Z+1 bugfix · X.Y+1.0 feature · X+1.0.0 breaking"
printf '\n'
ask NEW_VERSION "Nuova versione (es. 0.3.0):"
[[ -z "$NEW_VERSION" ]] && { warn "Versione vuota. Riavvia lo script."; exit 1; }
TAG="v${NEW_VERSION}"
say "Tag che verrà creato: ${BOLD}${TAG}${RESET}"
confirm "Procedi con la versione ${NEW_VERSION}?" || exit 1

# ── Stage 3: Aggiorna package.json ───────────────────────────────────────
stage "Aggiorna package.json"
say "Aggiornamento versione in electron/package.json..."
node -e "
  const fs = require('fs');
  const p = JSON.parse(fs.readFileSync('$PACKAGE_JSON', 'utf8'));
  p.version = '$NEW_VERSION';
  fs.writeFileSync('$PACKAGE_JSON', JSON.stringify(p, null, 2) + '\n');
"
printf '\n'
say "Diff:"
git -C "$REPO_ROOT" diff electron/package.json
printf '\n'
confirm "Il diff è corretto?" || { git -C "$REPO_ROOT" checkout -- electron/package.json; say "Annullato."; exit 1; }

# ── Stage 4: Commit e push main ──────────────────────────────────────────
stage "Commit e push main"
git -C "$REPO_ROOT" add electron/package.json
say "File in staging:"
git -C "$REPO_ROOT" status --short
printf '\n'
confirm "Committare con messaggio \"chore: bump version to ${NEW_VERSION}\"?" || exit 1
git -C "$REPO_ROOT" commit -m "chore: bump version to $NEW_VERSION"
say "Push su main..."
git -C "$REPO_ROOT" push origin main
say "${GREEN}✓ Push completato.${RESET}"

# ── Stage 5: Tag e push ───────────────────────────────────────────────────
stage "Tag: ${TAG}"
note "Il push del tag avvia il workflow CI che:"
note "  1. Esegue i test"
note "  2. Crea una release draft su GitHub"
note "  3. Builda gli artefatti su macOS, Windows e Linux"
note "  4. Allega gli artefatti alla release draft"
printf '\n'
confirm "Creare e pushare il tag ${TAG}?" || exit 1
git -C "$REPO_ROOT" tag "$TAG"
git -C "$REPO_ROOT" push origin "$TAG"
say "${GREEN}✓ Tag ${TAG} pushato. Il workflow Release è partito.${RESET}"

# ── Stage 6: Monitora CI ─────────────────────────────────────────────────
stage "Monitora CI"
say "Il workflow esegue test + build su macOS, Windows e Linux."
note "Tempo stimato: 10–20 minuti."
open_url "https://github.com/tizianocappai/finance-journal/actions"
step "Attendi che tutti i job siano verdi."
step "Se un job fallisce, leggi il log e correggi prima di ripubblicare."
printf '\n'
pause "Premi Enter quando il workflow è completato con successo."

# ── Stage 7: Pubblica release draft ──────────────────────────────────────
stage "Pubblica release"
say "Il CI ha creato una release in bozza su GitHub. Va pubblicata."
note "Puoi fornire le note qui oppure aprire il browser per il form completo."
printf '\n'
ask RELEASE_NOTES "Note di rilascio (Invio per usare il browser):"

if [[ -n "$RELEASE_NOTES" ]]; then
  gh release edit "$TAG" \
    --draft=false \
    --title "No Budget ${TAG}" \
    --notes "$RELEASE_NOTES"
  say "${GREEN}✓ Release ${TAG} pubblicata.${RESET}"
  open_url "https://github.com/tizianocappai/finance-journal/releases/tag/${TAG}"
else
  open_url "https://github.com/tizianocappai/finance-journal/releases/tag/${TAG}"
  step "Clicca il pulsante 'Edit release' (icona matita)."
  step "Aggiungi le note nella casella 'Describe this release'."
  step "Rimuovi il segno di spunta da 'Set as a pre-release' se presente."
  step "Clicca 'Publish release'."
  pause "Premi Enter quando la release è pubblicata."
fi

say "Verifica finale:"
open_url "https://github.com/tizianocappai/finance-journal/releases"
step "Controlla che gli artefatti siano presenti per tutte le piattaforme."
step "Scarica e installa il pacchetto per la tua piattaforma (vedi INSTALL.md)."
pause "Tutto OK? Premi Enter per completare."

finish
